


GET http://localhost:3000/users



# GET http://localhost:3000/users/67d465f9c360e860b282ccf6

# POST http://localhost:3000/users HTTP/1.1

# content-type: application/json
# {
#     "firstName": "Ash",
#    "lastName": "Vigo",
#     "email": "test@example.com",
#     "favoriteColor": "violeta",
#     "birthday": "September 26",
        
#  }




# PUT http://localhost:3000/users/67d465f9c360e860b282ccf6 HTTP/1.1

# content-type:application/json

# {
#     "firstName": "Ash",
#    "lastName": "Vigo",
#     "email": "test@example.com",
#     "favoriteColor": "violeta",
#     "birthday": "September 26",
     
# }

DELETE http://localhost:3000/users/67ed7386b9c6b1f24a2d5573 HTTP/1.1    

{
    "firstName": null,
    "lastName": null,
    "email": null,
    "favoriteColor": null,
    "birthday": null

}